name: Reproduce Bug

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    name: Build and Run
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          submodules: true

      - name: Set up cmake and ninja
        uses: lukka/get-cmake@582a9f5c6f4f332f36797e1ac757d1c8850a1513 # v3.30.4

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@5e0cab206a5ea620130caf672fce3e4a6b5666a1 # v11.5

      - name: Build
        run: |
          cmake --preset Default
          cmake --build build

      - name: Run
        run: ./build/bug-repro